services:
  - name: api
    type: web
    env: docker
    repo: https://github.com/Engr-DAN-org/attendance-system-api
    branch: main
    dockerfilePath: ./api/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    pullRequestPreviewsEnabled: true
